# 应用服务 WEB 访问端口
server:
  port: 4100

# 应用名称
spring:
  application:
    name: dingtalk-alert


dubbo:
  application:
    id: dingtalk-alert-service
    name: dingtalk-alert-service
  protocol:
    id: dubbo
    name: dubbo
    port: 20880
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  scan:
    basePackages: com.rany.ops.alert.api

