server:
  port: 3388
# 应用名称
spring:
  application:
    name: dingtalk-alert-service


dubbo:
  application:
    id: dingtalk-alert-service
    name: dingtalk-alert-service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://127.0.0.1:2181
  metadata-report:
    address: zookeeper://127.0.0.1:2181
  scan:
    basePackages: com.rany.ops.alert.api

