server:
  port: 3388

dubbo:
  config-center:
    address: zookeeper://zookeeper:2181
  registry:
    address: zookeeper://zookeeper:2181
    timeout: 30000
  metadata-report:
    address: zookeeper://zookeeper:2181
    timeout: 30000